"""Add Order model

Revision ID: 0d4bb4389dcb
Revises: 
Create Date: 2025-01-26 23:37:25.649940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d4bb4389dcb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    op.drop_table('pesanan')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pesanan',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nama', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('tanggal', sa.VARCHAR(length=100), nullable=True),
    sa.Column('jumlah', sa.INTEGER(), nullable=True),
    sa.Column('produk', sa.VARCHAR(length=100), nullable=True),
    sa.Column('harga', sa.FLOAT(), nullable=True),
    sa.Column('total_harga', sa.FLOAT(), nullable=True),
    sa.Column('pesan', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('produk', sa.VARCHAR(length=100), nullable=True),
    sa.Column('jumlah', sa.INTEGER(), nullable=True),
    sa.Column('total_harga', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
